### ISSUE TITLE
Tidal no longer working?

### ISSUE THREAD

**Issue by nicholasRutherford** [nickpwhite/Beatnik#16]
# Description

When you share a Tidal link from the android app you get the following:
- Track: https://tidal.com/track/73386152
- Artist: https://tidal.com/artist/5448076
- Album: https://tidal.com/album/73386149

On the web they create the following share URLs
- Track: https://tidal.com/browse/track/73386154
- Artist: https://tidal.com/browse/artist/5448076
- Album: https://tidal.com/browse/album/73386149

Neither of these url schemes seem to work anymore. I get this page:
![image](https://user-images.githubusercontent.com/4751193/93231372-8975a900-f72d-11ea-9ea6-e6c8ae8b9341.png)

Which doesn't look like a 0 result page nor a song page.

If I search for the same song via spotify `https://open.spotify.com/track/5RbZavmxaaEGRLHSy0f4xm` I get this result page: https://www.beatnikapp.com/music/2144. Which looks great, except that it doesn't have any Tidal links :(

**Comment by nickpwhite** [comment]
I don't think I saw this before until just now, sorry! I'm not sure what the issue was with the web links and getting links for Tidal but I think I fixed that with an API version bump in December in [this commit](https://github.com/nickpwhite/Beatnik/commit/17dc95f009a7901a6ebf2df4e76e1cec11638f2f).

I didn't realize the app used different share links than the web, but [this commit](https://github.com/nickpwhite/Beatnik/commit/d69af68c84021edadfb57d9dfc2d2b402fdb3db7) adds support for those, that should be deployed now.

Thanks @nicholasRutherford!
